/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.upwork.integrationplatform.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)")
public class TtestList implements org.apache.thrift.TBase<TtestList, TtestList._Fields>, java.io.Serializable, Cloneable, Comparable<TtestList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TtestList");

  private static final org.apache.thrift.protocol.TField TESTS_FIELD_DESC = new org.apache.thrift.protocol.TField("tests", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TtestListStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TtestListTupleSchemeFactory();

  private @org.apache.thrift.annotation.Nullable java.util.List<Ttest> tests; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TESTS((short)1, "tests");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TESTS
          return TESTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TESTS, new org.apache.thrift.meta_data.FieldMetaData("tests", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Ttest.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TtestList.class, metaDataMap);
  }

  public TtestList() {
  }

  public TtestList(
    java.util.List<Ttest> tests)
  {
    this();
    this.tests = tests;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TtestList(TtestList other) {
    if (other.isSetTests()) {
      java.util.List<Ttest> __this__tests = new java.util.ArrayList<Ttest>(other.tests.size());
      for (Ttest other_element : other.tests) {
        __this__tests.add(new Ttest(other_element));
      }
      this.tests = __this__tests;
    }
  }

  public TtestList deepCopy() {
    return new TtestList(this);
  }

  @Override
  public void clear() {
    this.tests = null;
  }

  public int getTestsSize() {
    return (this.tests == null) ? 0 : this.tests.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<Ttest> getTestsIterator() {
    return (this.tests == null) ? null : this.tests.iterator();
  }

  public void addToTests(Ttest elem) {
    if (this.tests == null) {
      this.tests = new java.util.ArrayList<Ttest>();
    }
    this.tests.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<Ttest> getTests() {
    return this.tests;
  }

  public void setTests(@org.apache.thrift.annotation.Nullable java.util.List<Ttest> tests) {
    this.tests = tests;
  }

  public void unsetTests() {
    this.tests = null;
  }

  /** Returns true if field tests is set (has been assigned a value) and false otherwise */
  public boolean isSetTests() {
    return this.tests != null;
  }

  public void setTestsIsSet(boolean value) {
    if (!value) {
      this.tests = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TESTS:
      if (value == null) {
        unsetTests();
      } else {
        setTests((java.util.List<Ttest>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TESTS:
      return getTests();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TESTS:
      return isSetTests();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TtestList)
      return this.equals((TtestList)that);
    return false;
  }

  public boolean equals(TtestList that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tests = true && this.isSetTests();
    boolean that_present_tests = true && that.isSetTests();
    if (this_present_tests || that_present_tests) {
      if (!(this_present_tests && that_present_tests))
        return false;
      if (!this.tests.equals(that.tests))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTests()) ? 131071 : 524287);
    if (isSetTests())
      hashCode = hashCode * 8191 + tests.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TtestList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTests()).compareTo(other.isSetTests());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTests()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tests, other.tests);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TtestList(");
    boolean first = true;

    sb.append("tests:");
    if (this.tests == null) {
      sb.append("null");
    } else {
      sb.append(this.tests);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TtestListStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TtestListStandardScheme getScheme() {
      return new TtestListStandardScheme();
    }
  }

  private static class TtestListStandardScheme extends org.apache.thrift.scheme.StandardScheme<TtestList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TtestList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TESTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.tests = new java.util.ArrayList<Ttest>(_list0.size);
                @org.apache.thrift.annotation.Nullable Ttest _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new Ttest();
                  _elem1.read(iprot);
                  struct.tests.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setTestsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TtestList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tests != null) {
        oprot.writeFieldBegin(TESTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tests.size()));
          for (Ttest _iter3 : struct.tests)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TtestListTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TtestListTupleScheme getScheme() {
      return new TtestListTupleScheme();
    }
  }

  private static class TtestListTupleScheme extends org.apache.thrift.scheme.TupleScheme<TtestList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TtestList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTests()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTests()) {
        {
          oprot.writeI32(struct.tests.size());
          for (Ttest _iter4 : struct.tests)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TtestList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tests = new java.util.ArrayList<Ttest>(_list5.size);
          @org.apache.thrift.annotation.Nullable Ttest _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new Ttest();
            _elem6.read(iprot);
            struct.tests.add(_elem6);
          }
        }
        struct.setTestsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

